waypoints:
  - position: #0
      x: -2.65
      y: -2.35
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -3.14
  - position: #1
      x: -3.0
      y: 3.5
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -1.57
  - position: #2
      x: 0.0
      y: 2.5
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -1.57


