waypoints:
  - position: #0
      x: 0.0
      y: 3.0
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
  - position: #1
      x: 6.0 
      y: 4.0
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.523
  - position: #2
      x: 6.5
      y: -1.4
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 3.1415
  - position: #3
      x: -1.6
      y: -2.5
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 1.309